name: Deploy to Heroku

on:
  push:
    branches:
      - main  # Thay main bằng tên branch mà bạn muốn triển khai từ đó

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Heroku
      run: heroku container:login

    - name: Build and push Docker image
      run: |
        docker build -t registry.heroku.com/adguardhome/web .
        docker push registry.heroku.com/adguardhome/web

    - name: Release image to Heroku
      run: heroku container:release web --app adguardhome
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
